name: Script Not Working
description: Report a script that isn't working properly after migration
title: "[BUG] Script issue: "
labels: ["bug"]
assignees:
  - ianandersonlol
body:
  - type: textarea
    id: script
    attributes:
      label: Script
      description: Paste your script content here
      placeholder: |
        #!/bin/bash
        #SBATCH --job-name=example
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What happened? What should have happened?
      description: Describe what went wrong and what you expected to happen
      placeholder: |
        The script fails with error message...
        I expected it to...
    validations:
      required: true